import pandas as pd
from filtro_por_ano import dataset_co2_FANO
df = dataset_co2_FANO['país'].unique() #Reporta todos os países listados
for i in df:
  print(i)
values_to_exclude = [
    "Asia",
    "Asia (GCP)",
    "Asia (excl. China and India)",
    "Africa",
    "Africa (GCP)",
    "Aland Islands",
    "American Samoa",
    "Aruba",
    "Bonaire Sint Eustatius and Saba",
    "Central America (GCP)",
    "Curacao",
    "Europe",
    "Europe (GCP)",
    "Europe (excl. EU-27)",
    "Europe (excl. EU-28)",
    "European Union (27)",
    "European Union (27) (GCP)",
    "European Union (28)",
    "French Equatorial Africa (GCP)",
    "French Equatorial Africa (Jones et al. 2023)",
    "French West Africa (GCP)",
    "French West Africa (Jones et al. 2023)",
    "High-income countries",
    "Anguilla",
    "Bermuda",
    "British Virgin Islands",
    "Christmas Island",
    "Cook Islands",
    "Falkland Islands",
    "Faroe Islands",
    "Greenland",
    "Guadeloupe",
    "Guernsey",
    "International transport",
    "Isle of Man",
    "Jersey",
    "Kuwaiti Oil Fires (GCP)",
    "Kuwaiti Oil Fires (Jones et al. 2023)",
    "Least developed countries (Jones et al. 2023)",
    "Leeward Islands (GCP)",
    "Leeward Islands (Jones et al. 2023)",
    "Low-income countries",
    "Lower-middle-income countries",
    "Macao",
    "Martinique",
    "Mayotte",
    "Middle East (GCP)",
    "Montserrat",
    "Netherlands Antilles",
    "New Caledonia",
    "Niue",
    "Non-OECD (GCP)",
    "North America",
    "North America (GCP)",
    "North America (excl. USA)",
    "OECD (GCP)",
    "OECD (Jones et al. 2023)",
    "Oceania",
    "Oceania (GCP)",
    "Panama Canal Zone (GCP)",
    "Panama Canal Zone (Jones et al. 2023)",
    "Reunion",
    "Ryukyu Islands (GCP)",
    "Ryukyu Islands (Jones et al. 2023)",
    "Saint Helena",
    "Saint Kitts and Nevis",
    "Saint Martin (French part)",
    "Puerto Rico",
    "Saint Pierre and Miquelon",
    "Sint Maarten (Dutch part)",
    "South America",
    "South America (GCP)",
    "St. Kitts-Nevis-Anguilla (GCP)",
    "St. Kitts-Nevis-Anguilla (Jones et al. 2023)",
    "Svalbard and Jan Mayen",
    "Turks and Caicos Islands",
    "United States Virgin Islands",
    "Upper-middle-income countries",
    "Wallis and Futuna",
    "Western Sahara",
    "World"
]

# Filtrando o DataFrame para excluir os registros com base na lista
dataset_co2_FPAIS = dataset_co2_FANO[~dataset_co2_FANO['país'].isin(values_to_exclude)]
dataset_co2_FPAIS.to_excel('co2_emissions_global_countries.xlsx', index=False)