import pandas as pd
from filtro_por_ano import dataset_co2_FANO
df = dataset_co2_FANO['país'].unique() #Reporte todos os países listados
for i in df:
  print(i)
values_to_exclude = [
    "Asia (GCP)",
    "Asia (excl. China and India)",
    "Africa (GCP)",
    "Aland Islands",
    "American Samoa",
    "Aruba",
    "Bonaire Sint Eustatius and Saba",
    "Curacao",
    "Europe (GCP)",
    "Europe (excl. EU-27)",
    "Europe (excl. EU-28)",
    "European Union (27)",
    "European Union (27) (GCP)",
    "French Equatorial Africa (GCP)",
    "French Equatorial Africa (Jones et al. 2023)",
    "French West Africa (GCP)",
    "French West Africa (Jones et al. 2023)",
    "Anguilla",
    "Bermuda",
    "British Virgin Islands",
    "Christmas Island",
    "Cook Islands",
    "Falkland Islands",
    "Faroe Islands",
    "Greenland",
    "Guadeloupe",
    "Guernsey",
    "Isle of Man",
    "Jersey",
    "Kuwaiti Oil Fires (GCP)",
    "Kuwaiti Oil Fires (Jones et al. 2023)",
    "Leeward Islands (GCP)",
    "Leeward Islands (Jones et al. 2023)",
    "Macao",
    "Martinique",
    "Mayotte",
    "Montserrat",
    "Netherlands Antilles",
    "New Caledonia",
    "Niue",
    "North America (GCP)",
    "North America (excl. USA)",
    "OECD (Jones et al. 2023)",
    "Oceania (GCP)",
    "Panama Canal Zone (GCP)",
    "Panama Canal Zone (Jones et al. 2023)",
    "Ryukyu Islands (GCP)",
    "Ryukyu Islands (Jones et al. 2023)",
    "Saint Helena",
    "Saint Kitts and Nevis",
    "Saint Martin (French part)",
    "Puerto Rico",
    "Reunion",
    "Saint Pierre and Miquelon",
    "Sint Maarten (Dutch part)",
    "South America (GCP)",
    "St. Kitts-Nevis-Anguilla (GCP)",
    "St. Kitts-Nevis-Anguilla (Jones et al. 2023)",
    "Svalbard and Jan Mayen",
    "Turks and Caicos Islands",
    "United States Virgin Islands",
    "Wallis and Futuna",
    "Western Sahara",
]

# Filtre o DataFrame para excluir os registros com base na lista
dataset_co2_FCONTINENTE = dataset_co2_FANO[~dataset_co2_FANO['país'].isin(values_to_exclude)]
values_to_include = [
    "Asia",
    "Africa",
    "Central America (GCP)",
    "Europe",
    "European Union (28)",
    "High-income countries",
    "International transport",
    "Least developed countries (Jones et al. 2023)",
    "Low-income countries",
    "Lower-middle-income countries",
    "Middle East (GCP)",
    "Non-OECD (GCP)",
    "North America",
    "OECD (GCP)",
    "Oceania",
    "South America",
    "Upper-middle-income countries",
    "World"
]
dataset_co2_FCONTINENTE = dataset_co2_FCONTINENTE[dataset_co2_FANO['país'].isin(values_to_include)]
dataset_co2_FCONTINENTE.to_excel('co2_emissions_global_continents.xlsx', index=False)